# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('api_token', models.CharField(max_length=100)),
                ('batch_id', models.IntegerField()),
            ],
        ),
    ]
