# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='api_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='batch_id',
            field=models.IntegerField(null=True),
        ),
    ]
